name: Mirror to GitLab SalesPilot

on:
  push:
    branches:
      - main
      - development

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to SalesPilot GitLab
        run: |
          git remote add gitlab https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@tools.ages.pucrs.br/salespilot/frontend.git
          
          git push gitlab HEAD:refs/heads/${{ github.ref_name }} --force